"""
Scans videos/ for subdirectories and writes tricks.js.

Expected layout:
  videos/
    kickflip/
      clip1.mp4
    fs180/
      clip1.mp4

Run from the repo root:
  python generate_tricks.py

Label and aliases are preserved from the existing tricks.js, keyed by
directory name (derived from clip paths). Only new tricks get a default label.
"""

import os
import re
import json

VIDEOS_DIR = "videos"
OUTPUT     = "tricks.js"
EXTS       = {".mp4", ".webm", ".mov"}


def load_existing_tricks():
    """
    Parse tricks.js and return an ordered list of dicts keyed by directory name:
      [{ "dirname": "fs180", "label": "frontside 180", "aliases": ["fs 180"] }, ...]
    Directory name is extracted from the first clip path in each trick block.
    """
    if not os.path.isfile(OUTPUT):
        return []

    with open(OUTPUT, encoding="utf-8") as f:
        content = f.read()

    existing = []
    for block in re.finditer(r'\{[^{]*?label:\s*"([^"]+)"[^{]*?aliases:\s*(\[[^\]]*\])[^{]*?"videos/([^/]+)/', content, re.DOTALL):
        label   = block.group(1)
        try:
            aliases = json.loads(block.group(2))
        except json.JSONDecodeError:
            aliases = []
        dirname = block.group(3)
        existing.append({"dirname": dirname, "label": label, "aliases": aliases})

    return existing


def main():
    existing      = load_existing_tricks()
    existing_map  = {e["dirname"]: e for e in existing}
    existing_dirs = [e["dirname"] for e in existing]

    if not os.path.isdir(VIDEOS_DIR):
        print(f"No '{VIDEOS_DIR}' directory found — nothing to do.")
        return

    # Collect all dirs that have clips
    all_dirs = {}
    for entry in os.scandir(VIDEOS_DIR):
        if not entry.is_dir():
            continue
        clips = sorted(
            f"{VIDEOS_DIR}/{entry.name}/{f}"
            for f in os.listdir(entry.path)
            if os.path.splitext(f)[1].lower() in EXTS
        )
        if clips:
            all_dirs[entry.name] = clips

    # Preserve existing order, then append new dirs sorted alphabetically
    new_dirs = sorted(d for d in all_dirs if d not in existing_map)
    ordered  = [d for d in existing_dirs if d in all_dirs] + new_dirs

    tricks = []
    for dirname in ordered:
        saved   = existing_map.get(dirname, {})
        label   = saved.get("label", dirname.replace("_", " ").replace("-", " "))
        aliases = saved.get("aliases", [])
        tricks.append({"label": label, "aliases": aliases, "clips": all_dirs[dirname]})

    lines = [
        "// Auto-generated by generate_tricks.py — do not edit by hand.",
        "// Run: python generate_tricks.py",
        "// Labels and aliases are preserved on re-run — edit them freely in this file.",
        "",
        "const tricks = [",
    ]

    for t in tricks:
        alias_json = json.dumps(t["aliases"])
        lines.append(f'  {{ label: {json.dumps(t["label"])}, aliases: {alias_json}, clips: [')
        for clip in t["clips"]:
            lines.append(f'    {json.dumps(clip)},')
        lines.append("  ]},")

    lines.append("];")
    lines.append("")

    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Wrote {len(tricks)} trick(s) to {OUTPUT}")
    for t in tricks:
        alias_str = f"  aliases: {t['aliases']}" if t["aliases"] else ""
        print(f"  {t['label']}: {len(t['clips'])} clip(s){alias_str}")


if __name__ == "__main__":
    main()
