// Auto-generated by generate_tricks.py — do not edit by hand.
// Run: python generate_tricks.py
// Labels and aliases are preserved on re-run — edit them freely in this file.

const tricks = [

  { label: "frontside pop shuvit", aliases: [], clips: [
    "videos/fsshuv/aimu.mp4",
  ]},

  { label: "kickflip", aliases: ["kf"], clips: [
    "videos/kickflip/aimu.mp4",
    "videos/kickflip/dylanjaeb.mp4",
  ]},
  { label: "heelflip", aliases: [], clips: [
    "videos/heelflip/dylanjaeb.mp4",
    "videos/heelflip/michaelsommer.mp4",
  ]},
  { label: "backside kickflip", aliases: [], clips: [
    "videos/bsflip/yuto.mp4",
  ]},
  { label: "frontside kickflip", aliases: [], clips: [
    "videos/fsflip/dylan.mp4",
  ]},
  { label: "backside heelflip", aliases: [], clips: [
    "videos/bsheel/michaelsommer.mp4",
    "videos/bsheel/michaelsommer_1.mp4",
    "videos/bsheel/michaelsommer_1667059367_2959828689447914794_5606397.mp4",
    "videos/bsheel/michaelsommer_1735760068_3536127074718371038_5606397.mp4",
  ]},
  { label: "frontside heelflip", aliases: [], clips: [
    "videos/fsheel/michaelsommer_2.mp4",
  ]},
  { label: "varial heelflip", aliases: [], clips: [
    "videos/varialheel/ikelow.mp4",
  ]},
  { label: "varial kickflip", aliases: [], clips: [
    "videos/varialkickflip/michaelsommer.mp4",
  ]},
  { label: "backside 360", aliases: [], clips: [
    "videos/bs360/aimu.mp4",
    "videos/bs360/ikelow.mp4",
  ]},
  { label: "360 flip", aliases: [], clips: [
    "videos/360flip/ike.mp4",
  ]},
  { label: "bigspin", aliases: [], clips: [
    "videos/bigspin/ike.mp4",
    "videos/bigspin/ike_1.mp4",
  ]},
  { label: "backside 360 kickflip", aliases: [], clips: [
    "videos/bs360flip/ike.mp4",
    "videos/bs360flip/ike_1.mp4",
  ]},
  { label: "hardflip", aliases: [], clips: [
    "videos/hardflip/dylanjaeb.mp4",
    "videos/hardflip/ike1.mp4",
    "videos/hardflip/michaelsommer_1.mp4",
  ]},

];
